<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRMo5ihQ\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRMo5ihQ/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRMo5ihQ.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRMo5ihQ\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerRMo5ihQ\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'RMo5ihQ',
    'container.build_id' => 'a8657e15',
    'container.build_time' => 1660372628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRMo5ihQ');
