<?php

namespace Customize\Repository;

use Customize\Entity\AnyProduct;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AnyProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnyProductRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, AnyProduct::class);
    }

}