<?php

namespace Customize\Repository;

use Customize\Entity\AnyProductCategory;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AnyProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnyProductCategoryRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, AnyProductCategory::class);
    }

}