<?php

namespace Customize\Repository;

use Customize\Entity\AnythingDetail;
use Eccube\Repository\AbstractRepository;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AnythingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnythingDetailRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, AnythingDetail::class);
    }

    
    public function newAnythingDetail()
    {

        $AnythingDetail = new \Customize\Entity\AnythingDetail();

        return $AnythingDetail;
    }

}