<?php

namespace Customize\Repository;

use Customize\Entity\Anything;
use Eccube\Repository\AbstractRepository;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AnythingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnythingRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, Anything::class);
    }

    
    public function newAnything()
    {

        $Anything = new \Customize\Entity\Anything();

        return $Anything;
    }


}