<?php

namespace Customize\Repository;

use Customize\Entity\Banner;
use Eccube\Repository\AbstractRepository;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, Banner::class);
    }

    
    public function newBanner()
    {

        $Banner = new \Customize\Entity\Banner();

        return $Banner;
    }


}