<?php

namespace Customize\Repository;

use Customize\Entity\StoreEntry;
use Eccube\Repository\AbstractRepository;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * StoreEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreEntryRepository extends AbstractRepository
{

    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, StoreEntry::class);
    }

    
    public function newStore()
    {

        $Store = new \Customize\Entity\StoreEntry();

        return $Store;
    }


}